# Generated by Django 2.0.1 on 2018-06-01 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Believe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('H', 'Mantiene esta creencia'), ('C', 'Cambió  completamente'), ('P', 'Cambió en parte')], default='H', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('date', models.DateField(blank=True, default='0001-01-01')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer'), ('O', 'Otro')], max_length=3)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('email_address', models.CharField(blank=True, max_length=130)),
                ('website', models.URLField(blank=True)),
                ('office_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=140)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=140)),
                ('family', models.ManyToManyField(blank=True, to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('email_address', models.CharField(blank=True, max_length=130)),
                ('website', models.URLField(blank=True)),
                ('office_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=140)),
                ('people', models.ManyToManyField(blank=True, related_name='party', to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('P', 'Incumplida deliberadamente'), ('N', 'Incumplida por inacción'), ('H', 'Incumplida en parte'), ('M', 'Cumplida en su mayoría'), ('A', 'Cumplida completamente')], default='N', max_length=3)),
                ('events', models.ManyToManyField(to='padres.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scandal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('events', models.ManyToManyField(to='padres.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url', models.URLField()),
                ('published_date', models.DateField(blank=True, default='0001-01-01')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('LC', 'Mentira Factual'), ('LO', 'Mentira por Omisión'), ('LF', 'Mentira por Influencia'), ('T', 'Es Cierto'), ('UN', 'No Verificado'), ('O', 'Opinión')], default='UN', max_length=3)),
                ('about_events', models.ManyToManyField(blank=True, to='padres.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('exact_statement', models.TextField()),
                ('date', models.DateField(blank=True, default='0001-01-01')),
                ('evidence', models.ManyToManyField(blank=True, to='padres.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='information',
            field=models.OneToOneField(on_delete='CASCADE', related_name='statement', to='padres.StatementInformation'),
        ),
        migrations.AddField(
            model_name='statement',
            name='people',
            field=models.ManyToManyField(related_name='statements', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='promise',
            name='information',
            field=models.OneToOneField(on_delete='CASCADE', to='padres.StatementInformation'),
        ),
        migrations.AddField(
            model_name='promise',
            name='people',
            field=models.ManyToManyField(related_name='promises', to='padres.Person'),
        ),
    ]
