# Generated by Django 2.0.1 on 2018-05-25 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('date', models.DateField(blank=True, default='0001-01-01')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=3)),
                ('name', models.CharField(max_length=140)),
                ('nickname', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=140)),
                ('family', models.ManyToManyField(to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=140, null=True)),
                ('people', models.ManyToManyField(to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url', models.URLField()),
                ('published_date', models.DateField(blank=True, default='0001-01-01')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scandal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('short_description', models.CharField(blank=True, max_length=140)),
                ('events', models.ManyToManyField(to='padres.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
