# Generated by Django 2.0.1 on 2018-02-09 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='actions',
            field=models.ManyToManyField(related_name='actions', to='padres.Event'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.ManyToManyField(related_name='benefits', to='padres.Event'),
        ),
        migrations.AddField(
            model_name='job',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='job',
            name='law_events',
            field=models.ManyToManyField(to='padres.Law_disorder'),
        ),
        migrations.AddField(
            model_name='job',
            name='pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ManyToManyField(to='padres.Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='promises',
            field=models.ManyToManyField(to='padres.Promise'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='padres.Job'),
        ),
    ]
