# Generated by Django 2.0.1 on 2018-05-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ownership',
            field=models.OneToOneField(blank=True, null=True, on_delete='PROTECT', to='transactions.Owner'),
        ),
        migrations.AddField(
            model_name='person',
            name='scandals',
            field=models.ManyToManyField(related_name='people', to='padres.Scandal'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(related_name='events', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='resources',
            field=models.ManyToManyField(to='padres.Resource'),
        ),
    ]
