# Generated by Django 2.0.1 on 2018-06-23 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('padres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete='PROTECT', related_name='uploaded_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statementinformation',
            name='evidence',
            field=models.ManyToManyField(blank=True, to='padres.Event'),
        ),
        migrations.AddField(
            model_name='statement',
            name='about_events',
            field=models.ManyToManyField(blank=True, to='padres.Event'),
        ),
        migrations.AddField(
            model_name='statement',
            name='information',
            field=models.OneToOneField(on_delete='CASCADE', related_name='statement', to='padres.StatementInformation'),
        ),
        migrations.AddField(
            model_name='statement',
            name='people',
            field=models.ManyToManyField(related_name='statements', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='scandal',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='promise',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='promise',
            name='information',
            field=models.OneToOneField(on_delete='CASCADE', to='padres.StatementInformation'),
        ),
        migrations.AddField(
            model_name='promise',
            name='people',
            field=models.ManyToManyField(related_name='promises', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='event_list',
            field=models.ManyToManyField(to='padres.EventList'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='party', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='event_list',
            field=models.ManyToManyField(to='padres.EventList'),
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ManyToManyField(blank=True, to='padres.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='ownership',
            field=models.OneToOneField(blank=True, on_delete='PROTECT', to='transactions.Owner'),
        ),
        migrations.AddField(
            model_name='person',
            name='scandals',
            field=models.ManyToManyField(blank=True, related_name='people', to='padres.Scandal'),
        ),
        migrations.AddField(
            model_name='image',
            name='people',
            field=models.ManyToManyField(to='padres.Person'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete='PROTECT', related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(related_name='events', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='sources',
            field=models.ManyToManyField(to='padres.Source'),
        ),
        migrations.AddField(
            model_name='believe',
            name='information',
            field=models.OneToOneField(on_delete='CASCADE', to='padres.StatementInformation'),
        ),
        migrations.AddField(
            model_name='believe',
            name='people',
            field=models.ManyToManyField(related_name='believes', to='padres.Person'),
        ),
    ]
