# Generated by Django 2.0.1 on 2018-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0002_auto_20180623_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
