# Generated by Django 2.0.1 on 2018-06-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padres', '0002_auto_20180601_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('url', models.URLField()),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='source',
            old_name='published_date',
            new_name='available_date',
        ),
        migrations.AddField(
            model_name='event',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='promise',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='last_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='source',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.Field(blank=True),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='website',
            field=models.Field(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='people',
            field=models.ManyToManyField(to='padres.Person'),
        ),
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete='PROTECT', related_name='uploaded_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='people',
            field=models.ManyToManyField(to='padres.Person'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete='PROTECT', related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='person',
            name='event_list',
            field=models.ManyToManyField(to='padres.EventList'),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='event_list',
            field=models.ManyToManyField(to='padres.EventList'),
        ),
    ]
