# Generated by Django 2.0.1 on 2018-05-04 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('padres', '0005_auto_20180503_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete='PROTECT', to='transactions.Owner'),
        ),
        migrations.AddField(
            model_name='person',
            name='short_description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='promise',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='scandal',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='scandal',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scandal',
            name='short_description',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='scandal',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Female')], max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Law_disorder',
        ),
    ]
