# Generated by Django 2.0.1 on 2018-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0006_auto_20180503_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default='0001-01-01'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=3),
        ),
    ]
