version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    image: padres-backend
    build: .
    container_name: dg01
    command:  bash -c "python manage.py runserver"
    depends_on:
      - db
    env_file: ./development.env
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
    
  db:
    image: postgres_d:latest
    container_name: ps1
    env_file: ./secret.env
