version: '2'
services:
  web:
    image: padres
    build: .
    container_name: dg01
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&  gunicorn wsgi:application -b 0.0.0.0:8000"
    env_file: ./production.env
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
