version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: ng12
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
  
    build: .
    container_name: dg1
    command: python manage.py runserver
    depends_on:
      - db
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
    
  db:
    image: postgres_d:latest
    container_name: ps1
    ports:
    -  "5432:5432"
    env_file: ./secret.env