# Generated by Django 2.0.1 on 2018-05-04 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0004_auto_20180213_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('short_description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('short_description', models.CharField(max_length=300)),
                ('event', models.ManyToManyField(to='padres.Event')),
                ('people', models.ManyToManyField(to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('vote', models.CharField(choices=[('y', 'vote of approval'), ('n', 'rejection vote'), ('a', 'absent from session'), ('r', 'refused to vote')], max_length=1)),
                ('reason', models.TextField()),
                ('bill', models.ForeignKey(on_delete='CASCADE', to='government.Bill')),
                ('person', models.ForeignKey(on_delete='CASCADE', to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='people',
            field=models.ManyToManyField(through='government.PersonBill', to='padres.Person'),
        ),
    ]
