# Generated by Django 2.0.1 on 2018-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbill',
            name='person',
            field=models.ForeignKey(on_delete='CASCADE', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='events',
            field=models.ManyToManyField(blank=True, to='padres.Event'),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='people',
            field=models.ManyToManyField(blank=True, to='padres.Person'),
        ),
        migrations.AddField(
            model_name='bill',
            name='people',
            field=models.ManyToManyField(through='government.PersonBill', to='padres.Person'),
        ),
    ]
