# Generated by Django 2.0.1 on 2018-06-19 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0003_auto_20180619_1533'),
        ('government', '0002_auto_20180601_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=130)),
                ('event_list', models.ManyToManyField(to='padres.EventList')),
                ('events', models.ManyToManyField(to='padres.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
