# Generated by Django 2.0.1 on 2018-06-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='transactions.BankAccount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='authorized_by',
            field=models.ManyToManyField(blank=True, to='padres.Person'),
        ),
    ]
