# Generated by Django 2.0.1 on 2018-05-21 14:17

import annoying.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180521_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='owners',
            field=models.ManyToManyField(blank=True, to='transactions.Owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(blank=True, to='transactions.Owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ownership',
            field=annoying.fields.AutoOneToOneField(default=1, on_delete='PROTECT', related_name='companies', to='transactions.Owner'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='owners',
            field=models.ManyToManyField(blank=True, to='transactions.Owner'),
        ),
    ]
