# Generated by Django 2.0.1 on 2018-05-21 14:44

import annoying.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20180521_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ownership',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete='PROTECT', related_name='companies', to='transactions.Owner'),
        ),
    ]
