# Generated by Django 2.0.1 on 2018-05-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20180523_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.CharField(choices=[('S', 'Salario'), ('C', 'Coima'), ('SIN', 'Sin Justificación'), ('B', 'Bono'), ('SOB', 'Soborno'), ('DON', 'Donación')], default='SIN', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='repetition',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
