# Generated by Django 2.0.1 on 2018-02-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('persons_role', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='termination_date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='title', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.ManyToManyField(related_name='benefits', to='padres.Event'),
        ),
        migrations.AddField(
            model_name='job',
            name='events',
            field=models.ManyToManyField(to='padres.Event'),
        ),
        migrations.AddField(
            model_name='job',
            name='institution',
            field=models.ForeignKey(default='government', on_delete=django.db.models.deletion.PROTECT, to='padres.Institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='pay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='padres.Job'),
        ),
        migrations.AddField(
            model_name='gig',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='padres.Job'),
        ),
        migrations.AddField(
            model_name='gig',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padres.Person'),
        ),
        migrations.AddField(
            model_name='job',
            name='person',
            field=models.ManyToManyField(through='padres.Gig', to='padres.Person'),
        ),
    ]
