# Generated by Django 2.0.1 on 2018-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0002_auto_20180207_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
