# Generated by Django 2.0.1 on 2018-02-13 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0003_auto_20180210_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='person',
            field=models.ManyToManyField(to='padres.Person'),
        ),
        migrations.AddField(
            model_name='promise',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
