# Generated by Django 2.0.1 on 2018-05-04 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('padres', '0004_auto_20180213_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.RemoveField(
            model_name='job',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='events',
        ),
        migrations.RemoveField(
            model_name='job',
            name='law_events',
        ),
        migrations.RemoveField(
            model_name='job',
            name='person',
        ),
        migrations.RemoveField(
            model_name='job',
            name='promises',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RenameField(
            model_name='promise',
            old_name='person',
            new_name='people',
        ),
        migrations.RemoveField(
            model_name='person',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='promise',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='people',
            field=models.ManyToManyField(to='padres.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
