# Generated by Django 2.0.1 on 2018-05-04 17:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0006_auto_20180503_1909'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongressJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=130, unique=True)),
                ('initial_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('pay', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovernmentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=130, unique=True)),
                ('initial_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('pay', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=130)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person_GovernmentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('government_job', models.ForeignKey(on_delete='CASCADE', to='jobs.GovernmentJob')),
                ('person', models.ForeignKey(on_delete='CASCADE', to='padres.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Person_PrivateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=130, unique=True)),
                ('initial_date', models.DateField()),
                ('termination_date', models.DateField()),
                ('pay', models.IntegerField(null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='transactions.Company')),
                ('people', models.ManyToManyField(blank=True, through='jobs.Person_PrivateJob', to='padres.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person_privatejob',
            name='government_job',
            field=models.ForeignKey(on_delete='CASCADE', to='jobs.PrivateJob'),
        ),
        migrations.AddField(
            model_name='person_privatejob',
            name='person',
            field=models.ForeignKey(on_delete='CASCADE', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='governmentjob',
            name='institution',
            field=models.ForeignKey(on_delete='PROTECT', to='jobs.Institution'),
        ),
        migrations.AddField(
            model_name='governmentjob',
            name='people',
            field=models.ManyToManyField(blank=True, through='jobs.Person_GovernmentJob', to='padres.Person'),
        ),
    ]
