# Generated by Django 2.0.1 on 2018-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
        ('jobs', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatejob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='transactions.Company'),
        ),
        migrations.AddField(
            model_name='privatejob',
            name='people',
            field=models.ManyToManyField(blank=True, through='jobs.Person_PrivateJob', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='person_privatejob',
            name='government_job',
            field=models.ForeignKey(on_delete='CASCADE', to='jobs.PrivateJob'),
        ),
        migrations.AddField(
            model_name='person_privatejob',
            name='person',
            field=models.ForeignKey(on_delete='CASCADE', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='person_governmentjob',
            name='government_job',
            field=models.ForeignKey(on_delete='CASCADE', to='jobs.GovernmentJob'),
        ),
        migrations.AddField(
            model_name='person_governmentjob',
            name='person',
            field=models.ForeignKey(on_delete='CASCADE', to='padres.Person'),
        ),
        migrations.AddField(
            model_name='governmentjob',
            name='institution',
            field=models.ForeignKey(on_delete='PROTECT', to='jobs.Institution'),
        ),
        migrations.AddField(
            model_name='governmentjob',
            name='people',
            field=models.ManyToManyField(blank=True, through='jobs.Person_GovernmentJob', to='padres.Person'),
        ),
    ]
