# Generated by Django 2.0.1 on 2018-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressjob',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='transactions.Payment'),
        ),
        migrations.AlterField(
            model_name='governmentjob',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='transactions.Payment'),
        ),
        migrations.AlterField(
            model_name='privatejob',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='transactions.Payment'),
        ),
    ]
