# Generated by Django 2.0.1 on 2018-06-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180601_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentjob',
            name='institution',
            field=models.ForeignKey(on_delete='PROTECT', to='government.Institution'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
