# Generated by Django 2.0.1 on 2018-05-21 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180521_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressjob',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='congressjob',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='governmentjob',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='governmentjob',
            name='termination_date',
        ),
        migrations.RemoveField(
            model_name='privatejob',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='privatejob',
            name='termination_date',
        ),
        migrations.AlterField(
            model_name='congressjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='governmentjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='privatejob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
