# Generated by Django 2.0.1 on 2018-05-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180521_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congressjob',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='governmentjob',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='privatejob',
            name='pay',
        ),
    ]
